spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=testDb
    username: admin
    password: 123
    hikari:
      maximum-pool-size: 10
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl